POST http://127.0.0.1:5055/api/auth/register
Content-Type: application/json

{
    "username": "alice",
    "password": "alice12345"
}

###

POST http://127.0.0.1:5055/api/auth/login
Content-Type: application/json

{
    "username": "alice",
    "password": "alice12345"
}


#  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4MTIyNWY1NWUzYWFkNjgyNWMxNDkiLCJpYXQiOjE3MTkxNDcxNjN9.OPjc_enz19RGVFd4Yv5ChA6jeEOAtZsJjHqC4MlbfbY",
#  "userId": "66781225f55e3aad6825c149"

###

POST http://127.0.0.1:5055/api/auth/create-todo-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4MTIyNWY1NWUzYWFkNjgyNWMxNDkiLCJpYXQiOjE3MTkxNDcxNjN9.OPjc_enz19RGVFd4Yv5ChA6jeEOAtZsJjHqC4MlbfbY

{
    "name": "Alice_Groceries1"
}


###

GET http://127.0.0.1:5055/api/todos/66781515d52547ec06052593
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4MTIyNWY1NWUzYWFkNjgyNWMxNDkiLCJpYXQiOjE3MTkxNDcxNjN9.OPjc_enz19RGVFd4Yv5ChA6jeEOAtZsJjHqC4MlbfbY


###

POST http://127.0.0.1:5055/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4MTIyNWY1NWUzYWFkNjgyNWMxNDkiLCJpYXQiOjE3MTkxNDcxNjN9.OPjc_enz19RGVFd4Yv5ChA6jeEOAtZsJjHqC4MlbfbY

{
  "title": "Buy groceries",
  "state": "TODO",
  "createdBy": "66781225f55e3aad6825c149",
  "todoListId": "66781515d52547ec06052593"
}


###


PUT http://127.0.0.1:5055/api/todos/66781515d52547ec06052593
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4MTIyNWY1NWUzYWFkNjgyNWMxNDkiLCJpYXQiOjE3MTkxNDcxNjN9.OPjc_enz19RGVFd4Yv5ChA6jeEOAtZsJjHqC4MlbfbY
Content-Type: application/json

{
  "state": "ONGOING"
}


###

POST http://127.0.0.1:5055/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4MTIyNWY1NWUzYWFkNjgyNWMxNDkiLCJpYXQiOjE3MTkxNDcxNjN9.OPjc_enz19RGVFd4Yv5ChA6jeEOAtZsJjHqC4MlbfbY

{
    "title": "Create todo list",
    "description": "Implement the functionality to create a todo list"
}

###

GET http://127.0.0.1:5055/api/todos
Authorization: Bearer $TOKEN$

###

GET http://127.0.0.1:5055/api/todos/1
Authorization: Bearer $TOKEN$

###

PUT http://127.0.0.1:5055/api/todos/1
Content-Type: application/json
Authorization: Bearer $TOKEN$
{
    "title": "Buy groceries",
    "description": "Milk, eggs, bread",
    "completed": true
}

###