name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./server
    - run: npm run build --if-present
      working-directory: ./server
    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
    - run: npm run test:ci
      working-directory: ./server
